#!/usr/bin/env bash

# Copyright 2019 Steven Dake
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export MC_HUB=${MC_HUB:-docker.io/sdake}
export MC_TAG=${MC_TAG:-sdake}

# define gsed as a function on Linux for compatibility
[ "$(uname -s)" == "Linux" ] && gsed() {
    sed "$@"
}

# Add a license header
print_license_header() {
    cat "license_header.txt" > $1.yaml
}

# add an autogenerated warning
print_autogenerated_warning() {
    cat<<EOF >> $1.yaml

# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# ----------------------------------------------------------
EOF
}

# Strip comments from microservices header
strip_headers() {
    grep -v '^#' "$1".yaml >> ${CLUSTER_NAME}.yaml
    echo "---" >> ${CLUSTER_NAME}.yaml
}

# Build manifests with hub and tag
mk_kubernetes_manifest() {
    print_license_header ${CLUSTER_NAME}
    print_autogenerated_warning ${CLUSTER_NAME}
    for svc in "$@"
    do
        strip_headers "../microservices-demo/kubernetes-manifests/${svc}"
        image="${MC_HUB}/${svc}:${MC_TAG}"
        pattern="^(\s*)image:\s.*$svc(.*)(\s*)"
        replace="\1image: $image\3"
        gsed -i -r "s|$pattern|$replace|g" ${CLUSTER_NAME}.yaml
    done
}

mk_istio_manifests() {
	# All other cloud providers work as is, except AWS
	print_license_header manifests/istio-generic
	print_autogenerated_warning manifests/istio-generic
	cat istio-1.1.7/install/kubernetes/helm/istio-init/files/crd-* >> manifests/istio-generic.yaml
	helm template istio-1.1.7/install/kubernetes/helm/istio --name istio --namespace istio-system -f istio/values/gateway-multicluster.yaml >> manifests/istio-generic.yaml

	# Override for AWS
	print_license_header manifests/istio-aws
	print_autogenerated_warning manifests/istio-aws
	cat istio-1.1.7/install/kubernetes/helm/istio-init/files/crd-* >> manifests/istio-aws.yaml
	helm template istio-1.1.7/install/kubernetes/helm/istio --name istio --namespace istio-system -f istio/values/gateway-multicluster.yaml -f istio/values/override-aws.yaml >> manifests/istio-aws.yaml
}

CLUSTER_NAME="manifests/azure"
AZURE_SVCS=("emailservice"
	"paymentservice"
	"shippingservice")
mk_kubernetes_manifest $AZURE_SVCS

CLUSTER_NAME="manifests/google"
GCP_SVCS=("frontend"
	"productcatalogservice"
	"recommendationservice")
	
mk_kubernetes_manifest $GCP_SVCS

CLUSTER_NAME="manifests/onprem"
ONPREM_SVCS=("adservice"
	"checkoutservice"
	"currencyservice"
	"cartservice"
	"currencyservice"
	"redis")

mk_kubernetes_manifest

mk_istio_manifests

# istio-currency goes into onprem
